/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@interface CSIBitmapWrapper : NSObject
{
    struct CGContext *_bitmapContext;
    NSData *_pixelData;
    unsigned int _pixelFormat;
    unsigned int _width;
    unsigned int _height;
    unsigned long long _rowbytes;
    BOOL _allowsMultiPassEncoding;
    BOOL _allowsOptimalRowbytesPacking;
    BOOL _allowsCompactCompression;
    BOOL _allowsPaletteImageCompression;
    BOOL _allowsHevcCompression;
    BOOL _allowsDeepmapImageCompression;
    BOOL _flipped;
    struct CGImage *_sourceImage;
    long long _texturePixelFormat;
    unsigned int _imageAlpha;
    double _compressionQuality;
    long long _compressionType;
    unsigned long long _colorSpaceID;
    long long _textureInterpretation;
    int _exifOrientation;
}

//@interface CSIBitmapWrapper : NSObject
//{
//    CGContextRef _bitmapContext;
//    NSData *_pixelData;
//    NSData *_rawData;
//    CSIPixelFormat _pixelFormat;
//    unsigned int _width;
//    unsigned int _height;
//    unsigned long long _rowbytes;
//    BOOL _allowsMultiPassEncoding;
//    unsigned int _imageAlpha;
//}

@property(nonatomic) CSIPixelFormat pixelFormat; // @synthesize pixelFormat=_pixelFormat;
@property BOOL allowsMultiPassEncoding; // @synthesize allowsMultiPassEncoding=_allowsMultiPassEncoding;
- (instancetype)initWithPixelWidth:(unsigned int)arg1 pixelHeight:(unsigned int)arg2;
- (NSArray <NSData *> *)compressedData:(BOOL)arg1 usedEncoding:(int *)arg2 andRowChunkSize:(unsigned int *)arg3;

- (NSData *)pixelData;
- (void)setPixelData:(NSData *)arg1;

- (unsigned int)sourceAlphaInfo;
- (void)setSourceAlphaInfo:(unsigned int)arg1;

- (CGContextRef)bitmapContext;
- (unsigned long long)rowbytes;
- (unsigned int)width;
- (unsigned int)height;

@end

