/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//!The different between this class and slice info is that this class actually defines
//! the difference between the "content" of a view/controller image and an "edge" for layout
//! purposes

// This class is unused by everything except CUIInternalLinkRendition
// so if we want to support classes that aren't internal links we can't use it
// and instead have to refer to documented metric information in the CSI header

// Not exported

@interface CUIRenditionMetrics : NSObject
{
    struct CGSize _imageSize;
    struct CGSize _edgeBottomLeftMargin;
    struct CGSize _edgeTopRightMargin;
    struct CGSize _contentBottomLeftMargin;
    struct CGSize _contentTopRightMargin;
    double _baseline;
    struct CGSize _auxiliary1BottomLeftMargin;
    struct CGSize _auxiliary1TopRightMargin;
    struct CGSize _auxiliary2BottomLeftMargin;
    struct CGSize _auxiliary2TopRightMargin;
    double _scale;
    struct crmFlags {
        unsigned int scalesVertically:1;
        unsigned int scalesHorizontally:1;
        unsigned int reserved:14;
    } _crmFlags;
}

- (BOOL)hasAlignmentEdgeMargins;
- (BOOL)hasOpaqueContentBounds;
- (struct CGRect)insetContentRectWithMetrics:(struct CGRect)arg1;
- (struct CGRect)insetRectWithMetrics:(struct CGRect)arg1;
- (struct CGRect)contentRect;
- (struct CGRect)edgeRect;
- (BOOL)scalesHorizontally;
- (BOOL)scalesVertically;
- (double)scale;
- (struct CGSize)auxiliary2TopRightMargin;
- (struct CGSize)auxiliary2BottomLeftMargin;
- (struct CGSize)auxiliary1TopRightMargin;
- (struct CGSize)auxiliary1BottomLeftMargin;
- (double)baseline;
- (struct CGSize)contentTopRightMargin;
- (struct CGSize)contentBottomLeftMargin;
- (struct CGSize)edgeTopRightMargin;
- (struct CGSize)edgeBottomLeftMargin;
- (struct CGSize)imageSize;
- (id)initWithImageSize:(struct CGSize)arg1 edgeBottomLeft:(struct CGSize)arg2 edgeTopRight:(struct CGSize)arg3 contentBottomLeft:(struct CGSize)arg4 contentTopRight:(struct CGSize)arg5 baseline:(double)arg6 auxiliary1BottomLeft:(struct CGSize)arg7 auxiliary1TopRight:(struct CGSize)arg8 auxiliary2BottomLeft:(struct CGSize)arg9 auxiliary2TopRight:(struct CGSize)arg10 scalesVertically:(BOOL)arg11 scalesHorizontally:(BOOL)arg12 scale:(double)arg13;
- (id)initwithImageSize:(struct CGSize)arg1 scale:(double)arg2;

@end

//@interface CUIRenditionMetrics : NSObject
//{
//    CGSize _imageSize;
//    CGSize _edgeBottomLeftMargin;
//    CGSize _edgeTopRightMargin;
//    CGSize _contentBottomLeftMargin;
//    CGSize _contentTopRightMargin;
//    double _baseline;
//    double _scale;
//    struct crmFlags {
//        unsigned int scalesVertically:1;
//        unsigned int scalesHorizontally:1;
//        unsigned int reserved:14;
//    } _crmFlags;
//}
//
//- (BOOL)hasAlignmentEdgeMargins;
//- (BOOL)hasOpaqueContentBounds;
//
//- (CGRect)insetContentRectWithMetrics:(CGRect)contentRect;
//- (CGRect)insetRectWithMetrics:(CGRect)edgeRect;
//- (CGRect)contentRect;
//- (CGRect)edgeRect;
//
//- (BOOL)scalesHorizontally;
//- (BOOL)scalesVertically;
//- (CGFloat)scale;
//- (CGFloat)baseline;
//
//- (CGSize)contentTopRightMargin;
//- (CGSize)contentBottomLeftMargin;
//- (CGSize)edgeTopRightMargin;
//- (CGSize)edgeBottomLeftMargin;
//- (CGSize)imageSize;
//
//- (instancetype)initWithImageSize:(CGSize)size edgeBottomLeft:(CGSize)ebl edgeTopRight:(CGSize)etr contentBottomLeft:(CGSize)cbl contentTopRight:(CGSize)ctr baseline:(CGFloat)baseline scalesVertically:(BOOL)vertically scalesHorizontally:(BOOL)horizontally scale:(CGFloat)scaleFactor;
//- (instancetype)initwithImageSize:(CGSize)arg1 scale:(CGFloat)arg2;
//
//@end
//
